
package wsimport.uk.ac.nerc.vocab;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import wsimport.uk.ac.nerc.vocab.types.*;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebService(name = "vocabv2", targetNamespace = "http://vocab.nerc.ac.uk")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Vocabv2 {


    /**
     * 
     * @param conceptSchemeURI
     * @return
     *     returns nerc.GetTopConceptsRet
     */
    @WebMethod(operationName = "GetTopConcepts", action = "http://vocab.nerc.ac.uk/GetTopConcepts")
    @WebResult(name = "getTopConcepts", targetNamespace = "")
    @RequestWrapper(localName = "GetTopConcepts", targetNamespace = "http://vocab.nerc.ac.uk/types", className = "wsimport.uk.ac.nerc.vocab.types.GetTopConcepts")
    @ResponseWrapper(localName = "GetTopConceptsResponse", targetNamespace = "http://vocab.nerc.ac.uk/types", className = "wsimport.uk.ac.nerc.vocab.types.GetTopConceptsResponse")
    public GetTopConceptsRet getTopConcepts(
        @WebParam(name = "conceptSchemeURI", targetNamespace = "")
        String conceptSchemeURI);

    /**
     * 
     * @param maxResults
     * @param query
     * @param uriList
     * @param termType
     * @param caseSensitivity
     * @param multilang
     * @param status
     * @return
     *     returns nerc.SearchResponse
     */
    @WebMethod(operationName = "SearchVocab", action = "http://vocab.nerc.ac.uk/SearchVocab")
    @WebResult(name = "searchResponse", targetNamespace = "")
    @RequestWrapper(localName = "SearchVocab", targetNamespace = "http://vocab.nerc.ac.uk/types", className = "wsimport.uk.ac.nerc.vocab.types.SearchVocab")
    @ResponseWrapper(localName = "SearchVocabResponse", targetNamespace = "http://vocab.nerc.ac.uk/types", className = "wsimport.uk.ac.nerc.vocab.types.SearchVocabResponse")
    public SearchResponse searchVocab(
        @WebParam(name = "query", targetNamespace = "")
        String query,
        @WebParam(name = "case_sensitivity", targetNamespace = "")
        String caseSensitivity,
        @WebParam(name = "term_type", targetNamespace = "")
        String termType,
        @WebParam(name = "max_results", targetNamespace = "")
        Integer maxResults,
        @WebParam(name = "multilang", targetNamespace = "")
        String multilang,
        @WebParam(name = "uri_list", targetNamespace = "")
        List<String> uriList,
        @WebParam(name = "status", targetNamespace = "")
        String status);

    /**
     * 
     * @param conceptURI
     * @return
     *     returns nerc.Concept
     */
    @WebMethod(operationName = "GetConcept", action = "http://vocab.nerc.ac.uk/GetConcept")
    @WebResult(name = "concept", targetNamespace = "")
    @RequestWrapper(localName = "GetConcept", targetNamespace = "http://vocab.nerc.ac.uk/types", className = "wsimport.uk.ac.nerc.vocab.types.GetConcept")
    @ResponseWrapper(localName = "GetConceptResponse", targetNamespace = "http://vocab.nerc.ac.uk/types", className = "wsimport.uk.ac.nerc.vocab.types.GetConceptResponse")
    public Concept getConcept(
        @WebParam(name = "conceptURI", targetNamespace = "")
        String conceptURI);

    /**
     * 
     * @param conceptSchemeURI
     * @return
     *     returns nerc.ConceptScheme
     */
    @WebMethod(operationName = "GetConceptScheme", action = "http://vocab.nerc.ac.uk/GetConceptScheme")
    @WebResult(name = "conceptScheme", targetNamespace = "")
    @RequestWrapper(localName = "GetConceptScheme", targetNamespace = "http://vocab.nerc.ac.uk/types", className = "wsimport.uk.ac.nerc.vocab.types.GetConceptScheme")
    @ResponseWrapper(localName = "GetConceptSchemeResponse", targetNamespace = "http://vocab.nerc.ac.uk/types", className = "wsimport.uk.ac.nerc.vocab.types.GetConceptSchemeResponse")
    public ConceptScheme getConceptScheme(
        @WebParam(name = "conceptSchemeURI", targetNamespace = "")
        String conceptSchemeURI);

    /**
     * 
     * @param conceptCollectionURI
     * @param status
     * @return
     *     returns nerc.ConceptCollection
     */
    @WebMethod(operationName = "GetConceptCollection", action = "http://vocab.nerc.ac.uk/GetConceptCollection")
    @WebResult(name = "conceptCollection", targetNamespace = "")
    @RequestWrapper(localName = "GetConceptCollection", targetNamespace = "http://vocab.nerc.ac.uk/types", className = "wsimport.uk.ac.nerc.vocab.types.GetConceptCollection")
    @ResponseWrapper(localName = "GetConceptCollectionResponse", targetNamespace = "http://vocab.nerc.ac.uk/types", className = "wsimport.uk.ac.nerc.vocab.types.GetConceptCollectionResponse")
    public ConceptCollection getConceptCollection(
        @WebParam(name = "conceptCollectionURI", targetNamespace = "")
        String conceptCollectionURI,
        @WebParam(name = "status", targetNamespace = "")
        String status);

    /**
     * 
     * @param collectionURI
     * @param conceptType
     * @param concept
     * @param status
     * @return
     *     returns nerc.VerifyConceptRet
     */
    @WebMethod(operationName = "VerifyConcept", action = "http://vocab.nerc.ac.uk/VerifyConcept")
    @WebResult(name = "verifyConcept", targetNamespace = "")
    @RequestWrapper(localName = "VerifyConcept", targetNamespace = "http://vocab.nerc.ac.uk/types", className = "wsimport.uk.ac.nerc.vocab.types.VerifyConcept")
    @ResponseWrapper(localName = "VerifyConceptResponse", targetNamespace = "http://vocab.nerc.ac.uk/types", className = "wsimport.uk.ac.nerc.vocab.types.VerifyConceptResponse")
    public VerifyConceptRet verifyConcept(
        @WebParam(name = "concept", targetNamespace = "")
        String concept,
        @WebParam(name = "collectionURI", targetNamespace = "")
        String collectionURI,
        @WebParam(name = "conceptType", targetNamespace = "")
        String conceptType,
        @WebParam(name = "status", targetNamespace = "")
        String status);

    /**
     * 
     * @param conceptURI
     * @param relationshipType
     * @param status
     * @return
     *     returns nerc.RelatedConcepts
     */
    @WebMethod(operationName = "GetRelatedConcepts", action = "http://vocab.nerc.ac.uk/GetRelatedConcepts")
    @WebResult(name = "relatedConcepts", targetNamespace = "")
    @RequestWrapper(localName = "GetRelatedConcepts", targetNamespace = "http://vocab.nerc.ac.uk/types", className = "wsimport.uk.ac.nerc.vocab.types.GetRelatedConcepts")
    @ResponseWrapper(localName = "GetRelatedConceptsResponse", targetNamespace = "http://vocab.nerc.ac.uk/types", className = "wsimport.uk.ac.nerc.vocab.types.GetRelatedConceptsResponse")
    public RelatedConcepts getRelatedConcepts(
        @WebParam(name = "conceptURI", targetNamespace = "")
        String conceptURI,
        @WebParam(name = "relationshipType", targetNamespace = "")
        String relationshipType,
        @WebParam(name = "status", targetNamespace = "")
        String status);

    /**
     * 
     * @return
     *     returns java.util.List<nerc.ConceptCollection>
     */
    @WebMethod(operationName = "GetCollections", action = "http://vocab.nerc.ac.uk/GetCollections")
    @WebResult(name = "collection", targetNamespace = "")
    @RequestWrapper(localName = "GetCollections", targetNamespace = "http://vocab.nerc.ac.uk/types", className = "wsimport.uk.ac.nerc.vocab.types.GetCollections")
    @ResponseWrapper(localName = "GetCollectionsResponse", targetNamespace = "http://vocab.nerc.ac.uk/types", className = "wsimport.uk.ac.nerc.vocab.types.GetCollectionsResponse")
    public List<ConceptCollection> getCollections();

    /**
     * 
     * @return
     *     returns java.util.List<nerc.ConceptScheme>
     */
    @WebMethod(operationName = "GetSchemes", action = "http://vocab.nerc.ac.uk/GetSchemes")
    @WebResult(name = "scheme", targetNamespace = "")
    @RequestWrapper(localName = "GetSchemes", targetNamespace = "http://vocab.nerc.ac.uk/types", className = "wsimport.uk.ac.nerc.vocab.types.GetSchemes")
    @ResponseWrapper(localName = "GetSchemesResponse", targetNamespace = "http://vocab.nerc.ac.uk/types", className = "wsimport.uk.ac.nerc.vocab.types.GetSchemesResponse")
    public List<ConceptScheme> getSchemes();

}
