package nl.maris2.seadatanet.webservices.edmerp;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2020-03-25T18:35:13.848+01:00
 * Generated source version: 3.1.8
 * 
 */
@WebServiceClient(name = "Edmerp", 
                  wsdlLocation = "https://edmerp.seadatanet.org/webservices/edmerp/edmerp.asmx?WSDL",
                  targetNamespace = "https://edmerp.seadatanet.org/webservices/edmerp/") 
public class Edmerp extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("https://edmerp.seadatanet.org/webservices/edmerp/", "Edmerp");
    public final static QName EdmerpSoap = new QName("https://edmerp.seadatanet.org/webservices/edmerp/", "EdmerpSoap");
    static {
        URL url = null;
        try {
            url = new URL("https://edmerp.seadatanet.org/webservices/edmerp/edmerp.asmx?WSDL");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Edmerp.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "https://edmerp.seadatanet.org/webservices/edmerp/edmerp.asmx?WSDL");
        }
        WSDL_LOCATION = url;
    }

    public Edmerp(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Edmerp(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Edmerp() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public Edmerp(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public Edmerp(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public Edmerp(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns EdmerpSoap
     */
    @WebEndpoint(name = "EdmerpSoap")
    public EdmerpSoap getEdmerpSoap() {
        return super.getPort(EdmerpSoap, EdmerpSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EdmerpSoap
     */
    @WebEndpoint(name = "EdmerpSoap")
    public EdmerpSoap getEdmerpSoap(WebServiceFeature... features) {
        return super.getPort(EdmerpSoap, EdmerpSoap.class, features);
    }

}
