//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-SNAPSHOT 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2017.01.18 at 05:01:34 PM CET 
//


package eu.seadatanet.org.edmerp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Address complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Address"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}delPoint" minOccurs="0"/&gt;
 *         &lt;element ref="{}city" minOccurs="0"/&gt;
 *         &lt;element ref="{}adminArea" minOccurs="0"/&gt;
 *         &lt;element ref="{}postCode" minOccurs="0"/&gt;
 *         &lt;element ref="{}country" minOccurs="0"/&gt;
 *         &lt;element ref="{}eMailAdd" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Address", propOrder = {
    "delPoint",
    "city",
    "adminArea",
    "postCode",
    "country",
    "eMailAdd"
})
public class Address {

    protected String delPoint;
    protected String city;
    protected String adminArea;
    protected String postCode;
    protected String country;
    protected String eMailAdd;

    /**
     * Gets the value of the delPoint property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDelPoint() {
        return delPoint;
    }

    /**
     * Sets the value of the delPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDelPoint(String value) {
        this.delPoint = value;
    }

    /**
     * Gets the value of the city property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCity() {
        return city;
    }

    /**
     * Sets the value of the city property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCity(String value) {
        this.city = value;
    }

    /**
     * Gets the value of the adminArea property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdminArea() {
        return adminArea;
    }

    /**
     * Sets the value of the adminArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdminArea(String value) {
        this.adminArea = value;
    }

    /**
     * Gets the value of the postCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostCode() {
        return postCode;
    }

    /**
     * Sets the value of the postCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostCode(String value) {
        this.postCode = value;
    }

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountry(String value) {
        this.country = value;
    }

    /**
     * Gets the value of the eMailAdd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEMailAdd() {
        return eMailAdd;
    }

    /**
     * Sets the value of the eMailAdd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEMailAdd(String value) {
        this.eMailAdd = value;
    }

}
