//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-SNAPSHOT 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2017.01.18 at 05:01:34 PM CET 
//


package eu.seadatanet.org.edmerp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}resTitle"/&gt;
 *         &lt;element ref="{}resAltTitle"/&gt;
 *         &lt;element ref="{}resRefDate"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "resTitle",
    "resAltTitle",
    "resRefDate"
})
@XmlRootElement(name = "aggrDSName")
public class AggrDSName {

    @XmlElement(required = true)
    protected String resTitle;
    @XmlElement(required = true)
    protected ResAltTitle resAltTitle;
    @XmlElement(required = true)
    protected DateRef resRefDate;

    /**
     * Gets the value of the resTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResTitle() {
        return resTitle;
    }

    /**
     * Sets the value of the resTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResTitle(String value) {
        this.resTitle = value;
    }

    /**
     * Gets the value of the resAltTitle property.
     * 
     * @return
     *     possible object is
     *     {@link ResAltTitle }
     *     
     */
    public ResAltTitle getResAltTitle() {
        return resAltTitle;
    }

    /**
     * Sets the value of the resAltTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResAltTitle }
     *     
     */
    public void setResAltTitle(ResAltTitle value) {
        this.resAltTitle = value;
    }

    /**
     * Gets the value of the resRefDate property.
     * 
     * @return
     *     possible object is
     *     {@link DateRef }
     *     
     */
    public DateRef getResRefDate() {
        return resRefDate;
    }

    /**
     * Sets the value of the resRefDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateRef }
     *     
     */
    public void setResRefDate(DateRef value) {
        this.resRefDate = value;
    }

}
