//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-SNAPSHOT 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2017.01.18 at 05:01:34 PM CET 
//


package eu.seadatanet.org.edmerp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}aggrDSName"/&gt;
 *         &lt;element ref="{}assocType"/&gt;
 *         &lt;element ref="{}initType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "aggrDSName",
    "assocType",
    "initType"
})
@XmlRootElement(name = "aggrInfo")
public class AggrInfo {

    @XmlElement(required = true)
    protected AggrDSName aggrDSName;
    @XmlElement(required = true)
    protected AssocType assocType;
    @XmlElement(required = true)
    protected InitType initType;

    /**
     * Gets the value of the aggrDSName property.
     * 
     * @return
     *     possible object is
     *     {@link AggrDSName }
     *     
     */
    public AggrDSName getAggrDSName() {
        return aggrDSName;
    }

    /**
     * Sets the value of the aggrDSName property.
     * 
     * @param value
     *     allowed object is
     *     {@link AggrDSName }
     *     
     */
    public void setAggrDSName(AggrDSName value) {
        this.aggrDSName = value;
    }

    /**
     * Gets the value of the assocType property.
     * 
     * @return
     *     possible object is
     *     {@link AssocType }
     *     
     */
    public AssocType getAssocType() {
        return assocType;
    }

    /**
     * Sets the value of the assocType property.
     * 
     * @param value
     *     allowed object is
     *     {@link AssocType }
     *     
     */
    public void setAssocType(AssocType value) {
        this.assocType = value;
    }

    /**
     * Gets the value of the initType property.
     * 
     * @return
     *     possible object is
     *     {@link InitType }
     *     
     */
    public InitType getInitType() {
        return initType;
    }

    /**
     * Sets the value of the initType property.
     * 
     * @param value
     *     allowed object is
     *     {@link InitType }
     *     
     */
    public void setInitType(InitType value) {
        this.initType = value;
    }

}
