//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-SNAPSHOT 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2017.01.18 at 05:01:34 PM CET 
//


package eu.seadatanet.org.edmerp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for citRespParty_lit complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="citRespParty_lit"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="rpIndName" type="{}element_rpIndName_lit" minOccurs="0"/&gt;
 *         &lt;element name="rpOrgName" type="{}element_rpOrgName_lit" minOccurs="0"/&gt;
 *         &lt;element ref="{}rpPosName" minOccurs="0"/&gt;
 *         &lt;element ref="{}rpCntInfo" minOccurs="0"/&gt;
 *         &lt;element ref="{}role"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "citRespParty_lit", propOrder = {
    "rpIndName",
    "rpOrgName",
    "rpPosName",
    "rpCntInfo",
    "role"
})
public class CitRespPartyLit {

    protected String rpIndName;
    protected String rpOrgName;
    protected String rpPosName;
    protected Contact rpCntInfo;
    @XmlElement(required = true)
    protected ElementRoleCd role;

    /**
     * Gets the value of the rpIndName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRpIndName() {
        return rpIndName;
    }

    /**
     * Sets the value of the rpIndName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRpIndName(String value) {
        this.rpIndName = value;
    }

    /**
     * Gets the value of the rpOrgName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRpOrgName() {
        return rpOrgName;
    }

    /**
     * Sets the value of the rpOrgName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRpOrgName(String value) {
        this.rpOrgName = value;
    }

    /**
     * Gets the value of the rpPosName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRpPosName() {
        return rpPosName;
    }

    /**
     * Sets the value of the rpPosName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRpPosName(String value) {
        this.rpPosName = value;
    }

    /**
     * Gets the value of the rpCntInfo property.
     * 
     * @return
     *     possible object is
     *     {@link Contact }
     *     
     */
    public Contact getRpCntInfo() {
        return rpCntInfo;
    }

    /**
     * Sets the value of the rpCntInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Contact }
     *     
     */
    public void setRpCntInfo(Contact value) {
        this.rpCntInfo = value;
    }

    /**
     * Gets the value of the role property.
     * 
     * @return
     *     possible object is
     *     {@link ElementRoleCd }
     *     
     */
    public ElementRoleCd getRole() {
        return role;
    }

    /**
     * Sets the value of the role property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElementRoleCd }
     *     
     */
    public void setRole(ElementRoleCd value) {
        this.role = value;
    }

}
