//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-SNAPSHOT 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2017.01.18 at 05:01:34 PM CET 
//


package eu.seadatanet.org.edmerp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Contact complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Contact"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}cntPhone" minOccurs="0"/&gt;
 *         &lt;element ref="{}cntAddress" minOccurs="0"/&gt;
 *         &lt;element ref="{}cntOnLineRes" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Contact", propOrder = {
    "cntPhone",
    "cntAddress",
    "cntOnLineRes"
})
public class Contact {

    protected Telephone cntPhone;
    protected Address cntAddress;
    protected OnlineRes cntOnLineRes;

    /**
     * Gets the value of the cntPhone property.
     * 
     * @return
     *     possible object is
     *     {@link Telephone }
     *     
     */
    public Telephone getCntPhone() {
        return cntPhone;
    }

    /**
     * Sets the value of the cntPhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link Telephone }
     *     
     */
    public void setCntPhone(Telephone value) {
        this.cntPhone = value;
    }

    /**
     * Gets the value of the cntAddress property.
     * 
     * @return
     *     possible object is
     *     {@link Address }
     *     
     */
    public Address getCntAddress() {
        return cntAddress;
    }

    /**
     * Sets the value of the cntAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link Address }
     *     
     */
    public void setCntAddress(Address value) {
        this.cntAddress = value;
    }

    /**
     * Gets the value of the cntOnLineRes property.
     * 
     * @return
     *     possible object is
     *     {@link OnlineRes }
     *     
     */
    public OnlineRes getCntOnLineRes() {
        return cntOnLineRes;
    }

    /**
     * Sets the value of the cntOnLineRes property.
     * 
     * @param value
     *     allowed object is
     *     {@link OnlineRes }
     *     
     */
    public void setCntOnLineRes(OnlineRes value) {
        this.cntOnLineRes = value;
    }

}
