//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-SNAPSHOT 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2017.01.18 at 05:01:34 PM CET 
//


package eu.seadatanet.org.edmerp;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DataIdent complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DataIdent"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}idCitation"/&gt;
 *         &lt;element ref="{}idAbs"/&gt;
 *         &lt;element ref="{}descKeys" maxOccurs="4" minOccurs="2"/&gt;
 *         &lt;element ref="{}dataLang"/&gt;
 *         &lt;element ref="{}tpCat"/&gt;
 *         &lt;element ref="{}dataExt" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DataIdent", propOrder = {
    "idCitation",
    "idAbs",
    "descKeys",
    "dataLang",
    "tpCat",
    "dataExt"
})
public class DataIdent {

    @XmlElement(required = true)
    protected Citation idCitation;
    @XmlElement(required = true)
    protected String idAbs;
    @XmlElement(required = true)
    protected List<Keywords> descKeys;
    @XmlElement(required = true)
    protected ElementLanguageCode dataLang;
    @XmlElement(required = true)
    protected ElementTopicCatCd tpCat;
    protected List<Extent> dataExt;

    /**
     * Gets the value of the idCitation property.
     * 
     * @return
     *     possible object is
     *     {@link Citation }
     *     
     */
    public Citation getIdCitation() {
        return idCitation;
    }

    /**
     * Sets the value of the idCitation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Citation }
     *     
     */
    public void setIdCitation(Citation value) {
        this.idCitation = value;
    }

    /**
     * Gets the value of the idAbs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdAbs() {
        return idAbs;
    }

    /**
     * Sets the value of the idAbs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdAbs(String value) {
        this.idAbs = value;
    }

    /**
     * Gets the value of the descKeys property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the descKeys property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescKeys().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Keywords }
     * 
     * 
     */
    public List<Keywords> getDescKeys() {
        if (descKeys == null) {
            descKeys = new ArrayList<Keywords>();
        }
        return this.descKeys;
    }

    /**
     * Gets the value of the dataLang property.
     * 
     * @return
     *     possible object is
     *     {@link ElementLanguageCode }
     *     
     */
    public ElementLanguageCode getDataLang() {
        return dataLang;
    }

    /**
     * Sets the value of the dataLang property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElementLanguageCode }
     *     
     */
    public void setDataLang(ElementLanguageCode value) {
        this.dataLang = value;
    }

    /**
     * Gets the value of the tpCat property.
     * 
     * @return
     *     possible object is
     *     {@link ElementTopicCatCd }
     *     
     */
    public ElementTopicCatCd getTpCat() {
        return tpCat;
    }

    /**
     * Sets the value of the tpCat property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElementTopicCatCd }
     *     
     */
    public void setTpCat(ElementTopicCatCd value) {
        this.tpCat = value;
    }

    /**
     * Gets the value of the dataExt property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dataExt property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDataExt().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Extent }
     * 
     * 
     */
    public List<Extent> getDataExt() {
        if (dataExt == null) {
            dataExt = new ArrayList<Extent>();
        }
        return this.dataExt;
    }

}
