//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-SNAPSHOT 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2017.01.18 at 05:01:34 PM CET 
//


package eu.seadatanet.org.edmerp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DateRef complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DateRef"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}refDate"/&gt;
 *         &lt;element ref="{}refDateType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DateRef", propOrder = {
    "refDate",
    "refDateType"
})
public class DateRef {

    @XmlElement(required = true)
    protected String refDate;
    @XmlElement(required = true)
    protected ElementDateTypCd refDateType;

    /**
     * Gets the value of the refDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefDate() {
        return refDate;
    }

    /**
     * Sets the value of the refDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefDate(String value) {
        this.refDate = value;
    }

    /**
     * Gets the value of the refDateType property.
     * 
     * @return
     *     possible object is
     *     {@link ElementDateTypCd }
     *     
     */
    public ElementDateTypCd getRefDateType() {
        return refDateType;
    }

    /**
     * Sets the value of the refDateType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElementDateTypCd }
     *     
     */
    public void setRefDateType(ElementDateTypCd value) {
        this.refDateType = value;
    }

}
