//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-SNAPSHOT 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2017.01.18 at 05:01:34 PM CET 
//


package eu.seadatanet.org.edmerp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Distrib complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Distrib"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}distTranOps" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Distrib", propOrder = {
    "distTranOps"
})
public class Distrib {

    protected DigTranOps distTranOps;

    /**
     * Gets the value of the distTranOps property.
     * 
     * @return
     *     possible object is
     *     {@link DigTranOps }
     *     
     */
    public DigTranOps getDistTranOps() {
        return distTranOps;
    }

    /**
     * Sets the value of the distTranOps property.
     * 
     * @param value
     *     allowed object is
     *     {@link DigTranOps }
     *     
     */
    public void setDistTranOps(DigTranOps value) {
        this.distTranOps = value;
    }

}
