//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-SNAPSHOT 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2017.01.18 at 05:01:34 PM CET 
//


package eu.seadatanet.org.edmerp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for element_Name complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="element_Name"&gt;
 *   &lt;simpleContent&gt;
 *     &lt;extension base="&lt;&gt;element_Name_Value"&gt;
 *       &lt;attribute name="SDNIdent" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/simpleContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "element_Name", propOrder = {
    "value"
})
public class ElementName {

    @XmlValue
    protected ElementNameValue value;
    @XmlAttribute(name = "SDNIdent", required = true)
    protected String sdnIdent;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link ElementNameValue }
     *     
     */
    public ElementNameValue getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElementNameValue }
     *     
     */
    public void setValue(ElementNameValue value) {
        this.value = value;
    }

    /**
     * Gets the value of the sdnIdent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSDNIdent() {
        return sdnIdent;
    }

    /**
     * Sets the value of the sdnIdent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSDNIdent(String value) {
        this.sdnIdent = value;
    }

}
