//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-SNAPSHOT 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2017.01.18 at 05:01:34 PM CET 
//


package eu.seadatanet.org.edmerp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ExtEleInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExtEleInfo"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}extEleName"/&gt;
 *         &lt;element ref="{}extEleDef"/&gt;
 *         &lt;element ref="{}eleDatatype"/&gt;
 *         &lt;element ref="{}extEleParEnt"/&gt;
 *         &lt;element ref="{}extEleSrc"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExtEleInfo", propOrder = {
    "extEleName",
    "extEleDef",
    "eleDatatype",
    "extEleParEnt",
    "extEleSrc"
})
public class ExtEleInfo {

    @XmlElement(required = true)
    protected String extEleName;
    @XmlElement(required = true)
    protected String extEleDef;
    @XmlElement(required = true)
    protected ElementDatatypeCd eleDatatype;
    @XmlElement(required = true)
    protected String extEleParEnt;
    @XmlElement(required = true)
    protected Citation extEleSrc;

    /**
     * Gets the value of the extEleName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtEleName() {
        return extEleName;
    }

    /**
     * Sets the value of the extEleName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtEleName(String value) {
        this.extEleName = value;
    }

    /**
     * Gets the value of the extEleDef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtEleDef() {
        return extEleDef;
    }

    /**
     * Sets the value of the extEleDef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtEleDef(String value) {
        this.extEleDef = value;
    }

    /**
     * Gets the value of the eleDatatype property.
     * 
     * @return
     *     possible object is
     *     {@link ElementDatatypeCd }
     *     
     */
    public ElementDatatypeCd getEleDatatype() {
        return eleDatatype;
    }

    /**
     * Sets the value of the eleDatatype property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElementDatatypeCd }
     *     
     */
    public void setEleDatatype(ElementDatatypeCd value) {
        this.eleDatatype = value;
    }

    /**
     * Gets the value of the extEleParEnt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtEleParEnt() {
        return extEleParEnt;
    }

    /**
     * Sets the value of the extEleParEnt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtEleParEnt(String value) {
        this.extEleParEnt = value;
    }

    /**
     * Gets the value of the extEleSrc property.
     * 
     * @return
     *     possible object is
     *     {@link Citation }
     *     
     */
    public Citation getExtEleSrc() {
        return extEleSrc;
    }

    /**
     * Sets the value of the extEleSrc property.
     * 
     * @param value
     *     allowed object is
     *     {@link Citation }
     *     
     */
    public void setExtEleSrc(Citation value) {
        this.extEleSrc = value;
    }

}
