//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-SNAPSHOT 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2017.01.18 at 05:01:34 PM CET 
//


package eu.seadatanet.org.edmerp;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Extent complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Extent"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}exDesc" minOccurs="0"/&gt;
 *         &lt;element ref="{}tempEle" minOccurs="0"/&gt;
 *         &lt;element ref="{}geoEle" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Extent", propOrder = {
    "exDesc",
    "tempEle",
    "geoEle"
})
public class Extent {

    protected String exDesc;
    protected TempExtentTypes tempEle;
    protected List<GeoExtentTypes> geoEle;

    /**
     * Gets the value of the exDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExDesc() {
        return exDesc;
    }

    /**
     * Sets the value of the exDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExDesc(String value) {
        this.exDesc = value;
    }

    /**
     * Gets the value of the tempEle property.
     * 
     * @return
     *     possible object is
     *     {@link TempExtentTypes }
     *     
     */
    public TempExtentTypes getTempEle() {
        return tempEle;
    }

    /**
     * Sets the value of the tempEle property.
     * 
     * @param value
     *     allowed object is
     *     {@link TempExtentTypes }
     *     
     */
    public void setTempEle(TempExtentTypes value) {
        this.tempEle = value;
    }

    /**
     * Gets the value of the geoEle property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the geoEle property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGeoEle().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GeoExtentTypes }
     * 
     * 
     */
    public List<GeoExtentTypes> getGeoEle() {
        if (geoEle == null) {
            geoEle = new ArrayList<GeoExtentTypes>();
        }
        return this.geoEle;
    }

}
