//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-SNAPSHOT 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2017.01.18 at 05:01:34 PM CET 
//


package eu.seadatanet.org.edmerp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GeoBndBox complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GeoBndBox"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element ref="{}westBL"/&gt;
 *         &lt;element ref="{}eastBL"/&gt;
 *         &lt;element ref="{}southBL"/&gt;
 *         &lt;element ref="{}northBL"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GeoBndBox", propOrder = {

})
public class GeoBndBox {

    @XmlElement(required = true)
    protected String westBL;
    @XmlElement(required = true)
    protected String eastBL;
    @XmlElement(required = true)
    protected String southBL;
    @XmlElement(required = true)
    protected String northBL;

    /**
     * Gets the value of the westBL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWestBL() {
        return westBL;
    }

    /**
     * Sets the value of the westBL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWestBL(String value) {
        this.westBL = value;
    }

    /**
     * Gets the value of the eastBL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEastBL() {
        return eastBL;
    }

    /**
     * Sets the value of the eastBL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEastBL(String value) {
        this.eastBL = value;
    }

    /**
     * Gets the value of the southBL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSouthBL() {
        return southBL;
    }

    /**
     * Sets the value of the southBL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSouthBL(String value) {
        this.southBL = value;
    }

    /**
     * Gets the value of the northBL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNorthBL() {
        return northBL;
    }

    /**
     * Sets the value of the northBL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNorthBL(String value) {
        this.northBL = value;
    }

}
