//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-SNAPSHOT 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2017.01.18 at 05:01:34 PM CET 
//


package eu.seadatanet.org.edmerp;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the eu.seadatanet.org.edmerp package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Metadata_QNAME = new QName("", "Metadata");
    private final static QName _MdFileID_QNAME = new QName("", "mdFileID");
    private final static QName _MdLang_QNAME = new QName("", "mdLang");
    private final static QName _MdChar_QNAME = new QName("", "mdChar");
    private final static QName _MdHrLv_QNAME = new QName("", "mdHrLv");
    private final static QName _MdHrLvName_QNAME = new QName("", "mdHrLvName");
    private final static QName _MdContact_QNAME = new QName("", "mdContact");
    private final static QName _MdDateSt_QNAME = new QName("", "mdDateSt");
    private final static QName _MdExtInfo_QNAME = new QName("", "mdExtInfo");
    private final static QName _DataIdInfo_QNAME = new QName("", "dataIdInfo");
    private final static QName _DistInfo_QNAME = new QName("", "distInfo");
    private final static QName _PorCatInfo_QNAME = new QName("", "porCatInfo");
    private final static QName _RpCntInfo_QNAME = new QName("", "rpCntInfo");
    private final static QName _CntPhone_QNAME = new QName("", "cntPhone");
    private final static QName _CntAddress_QNAME = new QName("", "cntAddress");
    private final static QName _CntOnLineRes_QNAME = new QName("", "cntOnLineRes");
    private final static QName _VoiceNum_QNAME = new QName("", "voiceNum");
    private final static QName _FaxNum_QNAME = new QName("", "faxNum");
    private final static QName _DelPoint_QNAME = new QName("", "delPoint");
    private final static QName _City_QNAME = new QName("", "city");
    private final static QName _AdminArea_QNAME = new QName("", "adminArea");
    private final static QName _PostCode_QNAME = new QName("", "postCode");
    private final static QName _Country_QNAME = new QName("", "country");
    private final static QName _EMailAdd_QNAME = new QName("", "eMailAdd");
    private final static QName _Linkage_QNAME = new QName("", "linkage");
    private final static QName _Role_QNAME = new QName("", "role");
    private final static QName _RpIndName_QNAME = new QName("", "rpIndName");
    private final static QName _ExtEleInfo_QNAME = new QName("", "extEleInfo");
    private final static QName _ExtEleName_QNAME = new QName("", "extEleName");
    private final static QName _ExtEleDef_QNAME = new QName("", "extEleDef");
    private final static QName _EleDatatype_QNAME = new QName("", "eleDatatype");
    private final static QName _ExtEleParEnt_QNAME = new QName("", "extEleParEnt");
    private final static QName _ExtEleSrc_QNAME = new QName("", "extEleSrc");
    private final static QName _CitRespParty_QNAME = new QName("", "citRespParty");
    private final static QName _ResTitle_QNAME = new QName("", "resTitle");
    private final static QName _ResRefDate_QNAME = new QName("", "resRefDate");
    private final static QName _ResEd_QNAME = new QName("", "resEd");
    private final static QName _CitId_QNAME = new QName("", "citId");
    private final static QName _RefDate_QNAME = new QName("", "refDate");
    private final static QName _RefDateType_QNAME = new QName("", "refDateType");
    private final static QName _IdCitation_QNAME = new QName("", "idCitation");
    private final static QName _IdAbs_QNAME = new QName("", "idAbs");
    private final static QName _IdPurp_QNAME = new QName("", "idPurp");
    private final static QName _DescKeys_QNAME = new QName("", "descKeys");
    private final static QName _KeyTyp_QNAME = new QName("", "keyTyp");
    private final static QName _ThesaName_QNAME = new QName("", "thesaName");
    private final static QName _ResConst_QNAME = new QName("", "resConst");
    private final static QName _ConstsTypes_QNAME = new QName("", "ConstsTypes");
    private final static QName _Consts_QNAME = new QName("", "Consts");
    private final static QName _BgFileType_QNAME = new QName("", "bgFileType");
    private final static QName _DataLang_QNAME = new QName("", "dataLang");
    private final static QName _TpCat_QNAME = new QName("", "tpCat");
    private final static QName _DataExt_QNAME = new QName("", "dataExt");
    private final static QName _TempEle_QNAME = new QName("", "tempEle");
    private final static QName _GeoEle_QNAME = new QName("", "geoEle");
    private final static QName _TempExtentTypes_QNAME = new QName("", "TempExtentTypes");
    private final static QName _GeoExtentTypes_QNAME = new QName("", "GeoExtentTypes");
    private final static QName _IdPoC_QNAME = new QName("", "idPoC");
    private final static QName _TempExtent_QNAME = new QName("", "TempExtent");
    private final static QName _ExDesc_QNAME = new QName("", "exDesc");
    private final static QName _ExTemp_QNAME = new QName("", "exTemp");
    private final static QName _TMPrimitive_QNAME = new QName("", "TM_Primitive");
    private final static QName _TMGeometricPrimitive_QNAME = new QName("", "TM_GeometricPrimitive");
    private final static QName _TMPeriod_QNAME = new QName("", "TM_Period");
    private final static QName _Begin_QNAME = new QName("", "begin");
    private final static QName _End_QNAME = new QName("", "end");
    private final static QName _DistTranOps_QNAME = new QName("", "distTranOps");
    private final static QName _OnLineSrc_QNAME = new QName("", "onLineSrc");
    private final static QName _GeoId_QNAME = new QName("", "geoId");
    private final static QName _IdentCode_QNAME = new QName("", "identCode");
    private final static QName _GeoBndBox_QNAME = new QName("", "GeoBndBox");
    private final static QName _WestBL_QNAME = new QName("", "westBL");
    private final static QName _EastBL_QNAME = new QName("", "eastBL");
    private final static QName _SouthBL_QNAME = new QName("", "southBL");
    private final static QName _NorthBL_QNAME = new QName("", "northBL");
    private final static QName _PortCatCit_QNAME = new QName("", "portCatCit");
    private final static QName _RpPosName_QNAME = new QName("", "rpPosName");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eu.seadatanet.org.edmerp
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Metadata }
     * 
     */
    public Metadata createMetadata() {
        return new Metadata();
    }

    /**
     * Create an instance of {@link ElementLanguageCode }
     * 
     */
    public ElementLanguageCode createElementLanguageCode() {
        return new ElementLanguageCode();
    }

    /**
     * Create an instance of {@link ElementCharSetCd }
     * 
     */
    public ElementCharSetCd createElementCharSetCd() {
        return new ElementCharSetCd();
    }

    /**
     * Create an instance of {@link ElementScopeCd }
     * 
     */
    public ElementScopeCd createElementScopeCd() {
        return new ElementScopeCd();
    }

    /**
     * Create an instance of {@link ElementName }
     * 
     */
    public ElementName createElementName() {
        return new ElementName();
    }

    /**
     * Create an instance of {@link RespParty }
     * 
     */
    public RespParty createRespParty() {
        return new RespParty();
    }

    /**
     * Create an instance of {@link MdExtInfo }
     * 
     */
    public MdExtInfo createMdExtInfo() {
        return new MdExtInfo();
    }

    /**
     * Create an instance of {@link DataIdent }
     * 
     */
    public DataIdent createDataIdent() {
        return new DataIdent();
    }

    /**
     * Create an instance of {@link Distrib }
     * 
     */
    public Distrib createDistrib() {
        return new Distrib();
    }

    /**
     * Create an instance of {@link PortCatRef }
     * 
     */
    public PortCatRef createPortCatRef() {
        return new PortCatRef();
    }

    /**
     * Create an instance of {@link CharSetCd }
     * 
     */
    public CharSetCd createCharSetCd() {
        return new CharSetCd();
    }

    /**
     * Create an instance of {@link ScopeCd }
     * 
     */
    public ScopeCd createScopeCd() {
        return new ScopeCd();
    }

    /**
     * Create an instance of {@link RpOrgName }
     * 
     */
    public RpOrgName createRpOrgName() {
        return new RpOrgName();
    }

    /**
     * Create an instance of {@link Contact }
     * 
     */
    public Contact createContact() {
        return new Contact();
    }

    /**
     * Create an instance of {@link Telephone }
     * 
     */
    public Telephone createTelephone() {
        return new Telephone();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link OnlineRes }
     * 
     */
    public OnlineRes createOnlineRes() {
        return new OnlineRes();
    }

    /**
     * Create an instance of {@link ElementRoleCd }
     * 
     */
    public ElementRoleCd createElementRoleCd() {
        return new ElementRoleCd();
    }

    /**
     * Create an instance of {@link RoleCd }
     * 
     */
    public RoleCd createRoleCd() {
        return new RoleCd();
    }

    /**
     * Create an instance of {@link ExtEleInfo }
     * 
     */
    public ExtEleInfo createExtEleInfo() {
        return new ExtEleInfo();
    }

    /**
     * Create an instance of {@link ElementDatatypeCd }
     * 
     */
    public ElementDatatypeCd createElementDatatypeCd() {
        return new ElementDatatypeCd();
    }

    /**
     * Create an instance of {@link DatatypeCd }
     * 
     */
    public DatatypeCd createDatatypeCd() {
        return new DatatypeCd();
    }

    /**
     * Create an instance of {@link Citation }
     * 
     */
    public Citation createCitation() {
        return new Citation();
    }

    /**
     * Create an instance of {@link ResAltTitle }
     * 
     */
    public ResAltTitle createResAltTitle() {
        return new ResAltTitle();
    }

    /**
     * Create an instance of {@link AggrInfo }
     * 
     */
    public AggrInfo createAggrInfo() {
        return new AggrInfo();
    }

    /**
     * Create an instance of {@link AggrDSName }
     * 
     */
    public AggrDSName createAggrDSName() {
        return new AggrDSName();
    }

    /**
     * Create an instance of {@link DateRef }
     * 
     */
    public DateRef createDateRef() {
        return new DateRef();
    }

    /**
     * Create an instance of {@link AssocType }
     * 
     */
    public AssocType createAssocType() {
        return new AssocType();
    }

    /**
     * Create an instance of {@link AscTypeCd }
     * 
     */
    public AscTypeCd createAscTypeCd() {
        return new AscTypeCd();
    }

    /**
     * Create an instance of {@link InitType }
     * 
     */
    public InitType createInitType() {
        return new InitType();
    }

    /**
     * Create an instance of {@link InitTypCd }
     * 
     */
    public InitTypCd createInitTypCd() {
        return new InitTypCd();
    }

    /**
     * Create an instance of {@link ElementDateTypCd }
     * 
     */
    public ElementDateTypCd createElementDateTypCd() {
        return new ElementDateTypCd();
    }

    /**
     * Create an instance of {@link DateTypCd }
     * 
     */
    public DateTypCd createDateTypCd() {
        return new DateTypCd();
    }

    /**
     * Create an instance of {@link Keywords }
     * 
     */
    public Keywords createKeywords() {
        return new Keywords();
    }

    /**
     * Create an instance of {@link Keyword }
     * 
     */
    public Keyword createKeyword() {
        return new Keyword();
    }

    /**
     * Create an instance of {@link ElementKeyTypCd }
     * 
     */
    public ElementKeyTypCd createElementKeyTypCd() {
        return new ElementKeyTypCd();
    }

    /**
     * Create an instance of {@link KeyTypCd }
     * 
     */
    public KeyTypCd createKeyTypCd() {
        return new KeyTypCd();
    }

    /**
     * Create an instance of {@link ConstsTypes }
     * 
     */
    public ConstsTypes createConstsTypes() {
        return new ConstsTypes();
    }

    /**
     * Create an instance of {@link Consts }
     * 
     */
    public Consts createConsts() {
        return new Consts();
    }

    /**
     * Create an instance of {@link UseLimit }
     * 
     */
    public UseLimit createUseLimit() {
        return new UseLimit();
    }

    /**
     * Create an instance of {@link ElementTopicCatCd }
     * 
     */
    public ElementTopicCatCd createElementTopicCatCd() {
        return new ElementTopicCatCd();
    }

    /**
     * Create an instance of {@link TopicCatCd }
     * 
     */
    public TopicCatCd createTopicCatCd() {
        return new TopicCatCd();
    }

    /**
     * Create an instance of {@link Extent }
     * 
     */
    public Extent createExtent() {
        return new Extent();
    }

    /**
     * Create an instance of {@link TempExtentTypes }
     * 
     */
    public TempExtentTypes createTempExtentTypes() {
        return new TempExtentTypes();
    }

    /**
     * Create an instance of {@link GeoExtentTypes }
     * 
     */
    public GeoExtentTypes createGeoExtentTypes() {
        return new GeoExtentTypes();
    }

    /**
     * Create an instance of {@link TempExtent }
     * 
     */
    public TempExtent createTempExtent() {
        return new TempExtent();
    }

    /**
     * Create an instance of {@link TMPrimitive }
     * 
     */
    public TMPrimitive createTMPrimitive() {
        return new TMPrimitive();
    }

    /**
     * Create an instance of {@link TMGeometricPrimitive }
     * 
     */
    public TMGeometricPrimitive createTMGeometricPrimitive() {
        return new TMGeometricPrimitive();
    }

    /**
     * Create an instance of {@link TMPeriod }
     * 
     */
    public TMPeriod createTMPeriod() {
        return new TMPeriod();
    }

    /**
     * Create an instance of {@link DigTranOps }
     * 
     */
    public DigTranOps createDigTranOps() {
        return new DigTranOps();
    }

    /**
     * Create an instance of {@link MdIdent }
     * 
     */
    public MdIdent createMdIdent() {
        return new MdIdent();
    }

    /**
     * Create an instance of {@link GeoBndBox }
     * 
     */
    public GeoBndBox createGeoBndBox() {
        return new GeoBndBox();
    }

    /**
     * Create an instance of {@link CitationLit }
     * 
     */
    public CitationLit createCitationLit() {
        return new CitationLit();
    }

    /**
     * Create an instance of {@link LanguageCode }
     * 
     */
    public LanguageCode createLanguageCode() {
        return new LanguageCode();
    }

    /**
     * Create an instance of {@link CitRespPartyLit }
     * 
     */
    public CitRespPartyLit createCitRespPartyLit() {
        return new CitRespPartyLit();
    }

    /**
     * Create an instance of {@link ElementExTemp }
     * 
     */
    public ElementExTemp createElementExTemp() {
        return new ElementExTemp();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Metadata }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Metadata")
    public JAXBElement<Metadata> createMetadata(Metadata value) {
        return new JAXBElement<Metadata>(_Metadata_QNAME, Metadata.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "mdFileID")
    public JAXBElement<String> createMdFileID(String value) {
        return new JAXBElement<String>(_MdFileID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ElementLanguageCode }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "mdLang")
    public JAXBElement<ElementLanguageCode> createMdLang(ElementLanguageCode value) {
        return new JAXBElement<ElementLanguageCode>(_MdLang_QNAME, ElementLanguageCode.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ElementCharSetCd }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "mdChar")
    public JAXBElement<ElementCharSetCd> createMdChar(ElementCharSetCd value) {
        return new JAXBElement<ElementCharSetCd>(_MdChar_QNAME, ElementCharSetCd.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ElementScopeCd }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "mdHrLv")
    public JAXBElement<ElementScopeCd> createMdHrLv(ElementScopeCd value) {
        return new JAXBElement<ElementScopeCd>(_MdHrLv_QNAME, ElementScopeCd.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ElementName }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "mdHrLvName")
    public JAXBElement<ElementName> createMdHrLvName(ElementName value) {
        return new JAXBElement<ElementName>(_MdHrLvName_QNAME, ElementName.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RespParty }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "mdContact")
    public JAXBElement<RespParty> createMdContact(RespParty value) {
        return new JAXBElement<RespParty>(_MdContact_QNAME, RespParty.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "mdDateSt")
    public JAXBElement<String> createMdDateSt(String value) {
        return new JAXBElement<String>(_MdDateSt_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MdExtInfo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "mdExtInfo")
    public JAXBElement<MdExtInfo> createMdExtInfo(MdExtInfo value) {
        return new JAXBElement<MdExtInfo>(_MdExtInfo_QNAME, MdExtInfo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DataIdent }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "dataIdInfo")
    public JAXBElement<DataIdent> createDataIdInfo(DataIdent value) {
        return new JAXBElement<DataIdent>(_DataIdInfo_QNAME, DataIdent.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Distrib }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "distInfo")
    public JAXBElement<Distrib> createDistInfo(Distrib value) {
        return new JAXBElement<Distrib>(_DistInfo_QNAME, Distrib.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PortCatRef }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "porCatInfo")
    public JAXBElement<PortCatRef> createPorCatInfo(PortCatRef value) {
        return new JAXBElement<PortCatRef>(_PorCatInfo_QNAME, PortCatRef.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Contact }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "rpCntInfo")
    public JAXBElement<Contact> createRpCntInfo(Contact value) {
        return new JAXBElement<Contact>(_RpCntInfo_QNAME, Contact.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Telephone }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "cntPhone")
    public JAXBElement<Telephone> createCntPhone(Telephone value) {
        return new JAXBElement<Telephone>(_CntPhone_QNAME, Telephone.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Address }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "cntAddress")
    public JAXBElement<Address> createCntAddress(Address value) {
        return new JAXBElement<Address>(_CntAddress_QNAME, Address.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OnlineRes }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "cntOnLineRes")
    public JAXBElement<OnlineRes> createCntOnLineRes(OnlineRes value) {
        return new JAXBElement<OnlineRes>(_CntOnLineRes_QNAME, OnlineRes.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "voiceNum")
    public JAXBElement<String> createVoiceNum(String value) {
        return new JAXBElement<String>(_VoiceNum_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "faxNum")
    public JAXBElement<String> createFaxNum(String value) {
        return new JAXBElement<String>(_FaxNum_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "delPoint")
    public JAXBElement<String> createDelPoint(String value) {
        return new JAXBElement<String>(_DelPoint_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "city")
    public JAXBElement<String> createCity(String value) {
        return new JAXBElement<String>(_City_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "adminArea")
    public JAXBElement<String> createAdminArea(String value) {
        return new JAXBElement<String>(_AdminArea_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "postCode")
    public JAXBElement<String> createPostCode(String value) {
        return new JAXBElement<String>(_PostCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "country")
    public JAXBElement<String> createCountry(String value) {
        return new JAXBElement<String>(_Country_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "eMailAdd")
    public JAXBElement<String> createEMailAdd(String value) {
        return new JAXBElement<String>(_EMailAdd_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "linkage")
    public JAXBElement<String> createLinkage(String value) {
        return new JAXBElement<String>(_Linkage_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ElementRoleCd }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "role")
    public JAXBElement<ElementRoleCd> createRole(ElementRoleCd value) {
        return new JAXBElement<ElementRoleCd>(_Role_QNAME, ElementRoleCd.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "rpIndName")
    public JAXBElement<String> createRpIndName(String value) {
        return new JAXBElement<String>(_RpIndName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExtEleInfo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "extEleInfo")
    public JAXBElement<ExtEleInfo> createExtEleInfo(ExtEleInfo value) {
        return new JAXBElement<ExtEleInfo>(_ExtEleInfo_QNAME, ExtEleInfo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "extEleName")
    public JAXBElement<String> createExtEleName(String value) {
        return new JAXBElement<String>(_ExtEleName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "extEleDef")
    public JAXBElement<String> createExtEleDef(String value) {
        return new JAXBElement<String>(_ExtEleDef_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ElementDatatypeCd }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "eleDatatype")
    public JAXBElement<ElementDatatypeCd> createEleDatatype(ElementDatatypeCd value) {
        return new JAXBElement<ElementDatatypeCd>(_EleDatatype_QNAME, ElementDatatypeCd.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "extEleParEnt")
    public JAXBElement<String> createExtEleParEnt(String value) {
        return new JAXBElement<String>(_ExtEleParEnt_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Citation }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "extEleSrc")
    public JAXBElement<Citation> createExtEleSrc(Citation value) {
        return new JAXBElement<Citation>(_ExtEleSrc_QNAME, Citation.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RespParty }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "citRespParty")
    public JAXBElement<RespParty> createCitRespParty(RespParty value) {
        return new JAXBElement<RespParty>(_CitRespParty_QNAME, RespParty.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "resTitle")
    public JAXBElement<String> createResTitle(String value) {
        return new JAXBElement<String>(_ResTitle_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DateRef }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "resRefDate")
    public JAXBElement<DateRef> createResRefDate(DateRef value) {
        return new JAXBElement<DateRef>(_ResRefDate_QNAME, DateRef.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "resEd")
    public JAXBElement<String> createResEd(String value) {
        return new JAXBElement<String>(_ResEd_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ElementCitId }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "citId")
    public JAXBElement<ElementCitId> createCitId(ElementCitId value) {
        return new JAXBElement<ElementCitId>(_CitId_QNAME, ElementCitId.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "refDate")
    public JAXBElement<String> createRefDate(String value) {
        return new JAXBElement<String>(_RefDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ElementDateTypCd }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "refDateType")
    public JAXBElement<ElementDateTypCd> createRefDateType(ElementDateTypCd value) {
        return new JAXBElement<ElementDateTypCd>(_RefDateType_QNAME, ElementDateTypCd.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Citation }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "idCitation")
    public JAXBElement<Citation> createIdCitation(Citation value) {
        return new JAXBElement<Citation>(_IdCitation_QNAME, Citation.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "idAbs")
    public JAXBElement<String> createIdAbs(String value) {
        return new JAXBElement<String>(_IdAbs_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "idPurp")
    public JAXBElement<String> createIdPurp(String value) {
        return new JAXBElement<String>(_IdPurp_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Keywords }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "descKeys")
    public JAXBElement<Keywords> createDescKeys(Keywords value) {
        return new JAXBElement<Keywords>(_DescKeys_QNAME, Keywords.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ElementKeyTypCd }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "keyTyp")
    public JAXBElement<ElementKeyTypCd> createKeyTyp(ElementKeyTypCd value) {
        return new JAXBElement<ElementKeyTypCd>(_KeyTyp_QNAME, ElementKeyTypCd.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Citation }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "thesaName")
    public JAXBElement<Citation> createThesaName(Citation value) {
        return new JAXBElement<Citation>(_ThesaName_QNAME, Citation.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConstsTypes }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "resConst")
    public JAXBElement<ConstsTypes> createResConst(ConstsTypes value) {
        return new JAXBElement<ConstsTypes>(_ResConst_QNAME, ConstsTypes.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ConstsTypes")
    public JAXBElement<Object> createConstsTypes(Object value) {
        return new JAXBElement<Object>(_ConstsTypes_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Consts }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Consts", substitutionHeadNamespace = "", substitutionHeadName = "ConstsTypes")
    public JAXBElement<Consts> createConsts(Consts value) {
        return new JAXBElement<Consts>(_Consts_QNAME, Consts.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "bgFileType")
    public JAXBElement<String> createBgFileType(String value) {
        return new JAXBElement<String>(_BgFileType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ElementLanguageCode }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "dataLang")
    public JAXBElement<ElementLanguageCode> createDataLang(ElementLanguageCode value) {
        return new JAXBElement<ElementLanguageCode>(_DataLang_QNAME, ElementLanguageCode.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ElementTopicCatCd }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "tpCat")
    public JAXBElement<ElementTopicCatCd> createTpCat(ElementTopicCatCd value) {
        return new JAXBElement<ElementTopicCatCd>(_TpCat_QNAME, ElementTopicCatCd.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Extent }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "dataExt")
    public JAXBElement<Extent> createDataExt(Extent value) {
        return new JAXBElement<Extent>(_DataExt_QNAME, Extent.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TempExtentTypes }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "tempEle")
    public JAXBElement<TempExtentTypes> createTempEle(TempExtentTypes value) {
        return new JAXBElement<TempExtentTypes>(_TempEle_QNAME, TempExtentTypes.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GeoExtentTypes }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "geoEle")
    public JAXBElement<GeoExtentTypes> createGeoEle(GeoExtentTypes value) {
        return new JAXBElement<GeoExtentTypes>(_GeoEle_QNAME, GeoExtentTypes.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TempExtentTypes")
    public JAXBElement<Object> createTempExtentTypes(Object value) {
        return new JAXBElement<Object>(_TempExtentTypes_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "GeoExtentTypes")
    public JAXBElement<Object> createGeoExtentTypes(Object value) {
        return new JAXBElement<Object>(_GeoExtentTypes_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RespParty }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "idPoC")
    public JAXBElement<RespParty> createIdPoC(RespParty value) {
        return new JAXBElement<RespParty>(_IdPoC_QNAME, RespParty.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TempExtent }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TempExtent", substitutionHeadNamespace = "", substitutionHeadName = "TempExtentTypes")
    public JAXBElement<TempExtent> createTempExtent(TempExtent value) {
        return new JAXBElement<TempExtent>(_TempExtent_QNAME, TempExtent.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "exDesc")
    public JAXBElement<String> createExDesc(String value) {
        return new JAXBElement<String>(_ExDesc_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TMPrimitive }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "exTemp")
    public JAXBElement<TMPrimitive> createExTemp(TMPrimitive value) {
        return new JAXBElement<TMPrimitive>(_ExTemp_QNAME, TMPrimitive.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TMGeometricPrimitive }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TM_Primitive")
    public JAXBElement<TMGeometricPrimitive> createTMPrimitive(TMGeometricPrimitive value) {
        return new JAXBElement<TMGeometricPrimitive>(_TMPrimitive_QNAME, TMGeometricPrimitive.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TMGeometricPrimitive }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TM_GeometricPrimitive", substitutionHeadNamespace = "", substitutionHeadName = "TM_Primitive")
    public JAXBElement<TMGeometricPrimitive> createTMGeometricPrimitive(TMGeometricPrimitive value) {
        return new JAXBElement<TMGeometricPrimitive>(_TMGeometricPrimitive_QNAME, TMGeometricPrimitive.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TMPeriod }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TM_Period")
    public JAXBElement<TMPeriod> createTMPeriod(TMPeriod value) {
        return new JAXBElement<TMPeriod>(_TMPeriod_QNAME, TMPeriod.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "begin")
    public JAXBElement<String> createBegin(String value) {
        return new JAXBElement<String>(_Begin_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "end")
    public JAXBElement<String> createEnd(String value) {
        return new JAXBElement<String>(_End_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DigTranOps }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "distTranOps")
    public JAXBElement<DigTranOps> createDistTranOps(DigTranOps value) {
        return new JAXBElement<DigTranOps>(_DistTranOps_QNAME, DigTranOps.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OnlineRes }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "onLineSrc")
    public JAXBElement<OnlineRes> createOnLineSrc(OnlineRes value) {
        return new JAXBElement<OnlineRes>(_OnLineSrc_QNAME, OnlineRes.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MdIdent }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "geoId", substitutionHeadNamespace = "", substitutionHeadName = "GeoExtentTypes")
    public JAXBElement<MdIdent> createGeoId(MdIdent value) {
        return new JAXBElement<MdIdent>(_GeoId_QNAME, MdIdent.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "identCode")
    public JAXBElement<String> createIdentCode(String value) {
        return new JAXBElement<String>(_IdentCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GeoBndBox }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "GeoBndBox", substitutionHeadNamespace = "", substitutionHeadName = "GeoExtentTypes")
    public JAXBElement<GeoBndBox> createGeoBndBox(GeoBndBox value) {
        return new JAXBElement<GeoBndBox>(_GeoBndBox_QNAME, GeoBndBox.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "westBL")
    public JAXBElement<String> createWestBL(String value) {
        return new JAXBElement<String>(_WestBL_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "eastBL")
    public JAXBElement<String> createEastBL(String value) {
        return new JAXBElement<String>(_EastBL_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "southBL")
    public JAXBElement<String> createSouthBL(String value) {
        return new JAXBElement<String>(_SouthBL_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "northBL")
    public JAXBElement<String> createNorthBL(String value) {
        return new JAXBElement<String>(_NorthBL_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CitationLit }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "portCatCit")
    public JAXBElement<CitationLit> createPortCatCit(CitationLit value) {
        return new JAXBElement<CitationLit>(_PortCatCit_QNAME, CitationLit.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "rpPosName")
    public JAXBElement<String> createRpPosName(String value) {
        return new JAXBElement<String>(_RpPosName_QNAME, String.class, null, value);
    }

}
