//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-SNAPSHOT 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2017.01.18 at 05:01:34 PM CET 
//


package eu.seadatanet.org.edmerp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Telephone complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Telephone"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}voiceNum" minOccurs="0"/&gt;
 *         &lt;element ref="{}faxNum" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Telephone", propOrder = {
    "voiceNum",
    "faxNum"
})
public class Telephone {

    protected String voiceNum;
    protected String faxNum;

    /**
     * Gets the value of the voiceNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVoiceNum() {
        return voiceNum;
    }

    /**
     * Sets the value of the voiceNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVoiceNum(String value) {
        this.voiceNum = value;
    }

    /**
     * Gets the value of the faxNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFaxNum() {
        return faxNum;
    }

    /**
     * Sets the value of the faxNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFaxNum(String value) {
        this.faxNum = value;
    }

}
