//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-SNAPSHOT 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2017.01.18 at 05:01:34 PM CET 
//


package eu.seadatanet.org.edmerp;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TM_Primitive complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TM_Primitive"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}TM_Primitive"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TM_Primitive", propOrder = {
    "tmPrimitive"
})
public class TMPrimitive {

    @XmlElementRef(name = "TM_Primitive", type = JAXBElement.class)
    protected JAXBElement<TMGeometricPrimitive> tmPrimitive;

    /**
     * Gets the value of the tmPrimitive property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link TMGeometricPrimitive }{@code >}
     *     {@link JAXBElement }{@code <}{@link TMGeometricPrimitive }{@code >}
     *     
     */
    public JAXBElement<TMGeometricPrimitive> getTMPrimitive() {
        return tmPrimitive;
    }

    /**
     * Sets the value of the tmPrimitive property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link TMGeometricPrimitive }{@code >}
     *     {@link JAXBElement }{@code <}{@link TMGeometricPrimitive }{@code >}
     *     
     */
    public void setTMPrimitive(JAXBElement<TMGeometricPrimitive> value) {
        this.tmPrimitive = value;
    }

}
